### ISSUE TITLE
Traceback when running fio - from Sai

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#1534]
I'm running pbench-fio and seeing the following tracebacks. Any idea, if something is wrong?

```
[root@f24-h18-000-r630 ~]# rpm -qa | grep pbench
pbench-perl-Types-Serialiser-1.0-1.noarch
pbench-fio-3.12-1.x86_64
pbench-perl-JSON-XS-4.02-1.x86_64
pbench-agent-0.67-1g3fb4270c.noarch
pbench-sysstat-12.0.3-1.x86_64
pbench-perl-common-sense-3.74-1.x86_64
pbench-agent-internal-0.67-1.noarch
==========================================
root@f24-h18-000-r630 ~]# pbench-fio --targets=/dev/sda --client-file file.txt --config=rhel7-off
verifying clients have fio installed
[error][2020-03-06T19:29:44.222615494] At least one client did not have block device /dev/sda, exiting
[root@f24-h18-000-r630 ~]# pbench-fio --targets=/dev/vda1 --client-file file.txt --config=rhel7-off
verifying clients have fio installed
Collecting system information
Created the following job file (/var/lib/pbench-agent/fio_rhel7-off_2020.03.06T19.30.15/1-read-4KiB/
fio.job):
[global]
bs=4k
runtime=30
ioengine=libaio
iodepth=32
direct=1
sync=0
time_based=1
clocksource=gettimeofday
ramp_time=5
write_bw_log=fio
write_iops_log=fio
write_lat_log=fio
log_avg_msec=1000
write_hist_log=fio
log_hist_msec=10000

[job-/dev/vda1]
filename=/dev/vda1
rw=read
size=4096M
numjobs=1

running fio job: /var/lib/pbench-agent/fio_rhel7-off_2020.03.06T19.30.15/1-read-4KiB/fio.job (sample1)
bash: firewall-cmd: command not found
Traceback (most recent call last):
  File "/usr/local/bin/fio-histo-log-pctiles.py", line 773, in <module>
    compute_percentiles_from_logs()
  File "/usr/local/bin/fio-histo-log-pctiles.py", line 479, in compute_percentiles_from_logs
    samples = get_samples(all_threads_histo_t)
  File "/usr/local/bin/fio-histo-log-pctiles.py", line 279, in get_samples
    return reduce( lambda x,y: x + y, buckets)
NameError: name 'reduce' is not defined
[fio-postprocess-viz.py] Chart Type: xy (/var/lib/pbench-agent/fio_rhel7-off_2020.03.06T19.30.15/
1-read-4KiB/sample1/clients/192.168.122.131/hist/results.html)
Traceback (most recent call last):
  File "/usr/local/bin/fio-histo-log-pctiles.py", line 773, in <module>
    compute_percentiles_from_logs()
  File "/usr/local/bin/fio-histo-log-pctiles.py", line 479, in compute_percentiles_from_logs
    samples = get_samples(all_threads_histo_t)
  File "/usr/local/bin/fio-histo-log-pctiles.py", line 279, in get_samples
    return reduce( lambda x,y: x + y, buckets)
NameError: name 'reduce' is not defined
```

**Comment by ndokos** [comment]
`reduce' has been deleted in Python3 - we have changed all of
pbench-agent to use python3. Although the fio-host-log-pctiles.py file
(that's part of the upstream fio) still uses reduce, it is explicitly
marked as a python2 program, so that *should* work, as long as you
have python2 as well as python3 on the box.

It may be an installation problem: when installing an RPM, I often
see the shebang lines changed (particularly on RHEL8) but it is
changing the generic /usr/bin/python to a specific /usr/bin/python2 or
/usr/bin/python3 - I don't think I've seen any changes from python2 to
python3.

So I'm not sure what's going on, but it would be worth to pursue this:
the first thing to do is to check
/usr/local/bin/fio-host-log-pctiles.py's shebang line.  Also version
info (OS, pbench-agent, fio) would be helpful.

**Comment by portante** [comment]
@ndokos, will this be fixed possibly by the 3.18 release of `fio`?

**Comment by ndokos** [comment]
I'm not sure what caused this, so I'm not sure whether it'll be fixed by anything that is (or will be) in v0,68. I think Sai is the only one who has seen it however, so I hope it was some peculiarity of his setup that caused it. I'll ping him and ask him to comment.

**Comment by smalleni** [comment]
shebang line on the pbench controller host (RHEL 7.7) is #!/usr/bin/env python for /usr/local/bin/fio-histo-log-pctiles.py

I see still see this issue with v0.67. The pbench controller is a RHEL 7.7 host and FIO client is a RHEL 8.1 guest.

Host
```
[root@f24-h18-000-r630 ~]# rpm -qa | grep pbench
pbench-perl-Types-Serialiser-1.0-1.noarch
pbench-fio-3.12-1.x86_64
pbench-perl-JSON-XS-4.02-1.x86_64
pbench-agent-0.67-1g3fb4270c.noarch
pbench-sysstat-12.0.3-1.x86_64
pbench-perl-common-sense-3.74-1.x86_64
pbench-agent-internal-0.67-1.noarch
```
Guest
```
[root@localhost ~]# rpm -qa | grep pbench
pbench-perl-JSON-XS-4.02-1.x86_64
pbench-perl-Types-Serialiser-1.0-1.noarch
pbench-agent-0.67-1g3fb4270c.noarch
pbench-sysstat-12.0.3-1.x86_64
pbench-fio-3.12-1.x86_64
pbench-perl-common-sense-3.74-1.x86_64
```

**Comment by ndokos** [comment]
@smalleni : 

- can you add the command line invocation of pbench-fio here?
- can  you check the version of the pbench-fio RPM that is installed on the RHEL7 system?
- assuming that it is 3.12, maybe you can try reinstalling it: the spec file explicitly applies a patch that changes that shebang line to `#! /usr/bin/python2` so I don't understand why yours is different.

**Comment by smalleni** [comment]
@ndokos All the info is in my previous comments.

Invocation: pbench-fio --targets=/dev/sda --client-file file.txt --config=rhel7-off
fio version: pbench-fio-3.12-1.x86_64

Will try step your 3rd suggestion.

**Comment by ndokos** [comment]
@smalleni: Yes, sorry - my bad.

**Comment by portante** [comment]
Not enough information to debug at this point.  This is likely due to problems with the old `pbench-fio` RPM we used to provide.
